name: "Build and Push Docker Image"

on: 
  push:
    branches: [ "main", "docker_images" ]
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Verificar o Dockerfile
      run: cat ./docker/Dockerfile

    - name: Listar arquivos no diret√≥rio atual
      run: ls -la
    
    - name: Build docker image
      run: |
        docker build --target=production -t leonardoitalo/django_api:${{ github.sha }} .